name: Dependency Review

on: 
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail if there are any vulnerable dependencies
          fail-on-severity: moderate
          # Allow only approved licenses
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
          # Deny specific licenses
          deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.0, LGPL-2.1, LGPL-3.0
          # Create a comment with the review results
          comment-summary-in-pr: true